---
name: Routing
shards:
- github: amberframework/amber-router
  mirrors:
  - github: amberframework/router
    role: legacy
- github: luislavena/beryl
  description: Action-focused HTTP routing library
- github: jreinert/crouter
  description: A standalone router
- github: repomaa/crouter
  description: A standalone router
- github: obsidian/orion
  description: A minimal, rails-esque routing library
- github: tbrand/router.cr
  description: Minimum but powerful http router for HTTP::Server
- github: athena-framework/routing
  description: HTTP based routing library/framework
- github: soveran/toro
  description: Tree Oriented Routing
